// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHkUQ7OY8MI8RgT7UVmRY6b4rPg0e4TT8',
    appId: '1:981223268552:web:4a541f6499c1b3a5af85fd',
    messagingSenderId: '981223268552',
    projectId: 'shipx-77cae',
    authDomain: 'shipx-77cae.firebaseapp.com',
    storageBucket: 'shipx-77cae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrpMHMxwRR1luHRDuaYof1JOpx8Pk6jWc',
    appId: '1:981223268552:android:990308b80f1613dfaf85fd',
    messagingSenderId: '981223268552',
    projectId: 'shipx-77cae',
    storageBucket: 'shipx-77cae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGhIXXj7cJpmA3qwLmYo41r0CbPvCSolI',
    appId: '1:981223268552:ios:70b209e5ad69412faf85fd',
    messagingSenderId: '981223268552',
    projectId: 'shipx-77cae',
    storageBucket: 'shipx-77cae.appspot.com',
    iosClientId: '981223268552-cmts9n2vle2kv400d8sg7d67qjtobque.apps.googleusercontent.com',
    iosBundleId: 'com.example.shipx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGhIXXj7cJpmA3qwLmYo41r0CbPvCSolI',
    appId: '1:981223268552:ios:eff2fc795aec4245af85fd',
    messagingSenderId: '981223268552',
    projectId: 'shipx-77cae',
    storageBucket: 'shipx-77cae.appspot.com',
    iosClientId: '981223268552-4finvavbmpgv9avip89vtik6idbt7fdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.shipx.RunnerTests',
  );
}
